title: Gemmule
description: General Mixed-Family Expectation Maximization
theme: just-the-docs
url: "https://mathornton01.github.io/gemmulem"
repository: mathornton01/gemmulem
search_enabled: true
nav_order: 1

plugins:
  - jekyll-seo-tag

# MathJax support
markdown: kramdown
kramdown:
  math_engine: mathjax

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/mathornton01/gemmulem

# Footer
footer_content: "Copyright &copy; 2024 Micah Thornton. Distributed under the <a href=\"https://opensource.org/licenses/MIT\">MIT license.</a>"

# Color scheme
color_scheme: light

# Aux links
aux_links:
  "GitHub":
    - "//github.com/mathornton01/gemmulem"

aux_links_new_tab: true

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
